wrlinux-image-glibc-std-sato:  drop wr-core-lsb-more/wr-core-lsb-graphics-plus on mips64n32
Issue: LIN8-1785

It had been disabled on mips64, now also disable it on mips64n32.

* qt4-x11-free do_compile failed, this patch skips building it:
./wtf/StdLibExtras.h: In instantiation of 'TO WTF::bitwise_cast(FROM) [with TO = int; FROM = double]':
runtime/JSValueInlineMethods.h:495:44: required from here
./wtf/Assertions.h:326:47: error: size of array is negative
 #define COMPILE_ASSERT(exp, name) typedef int dummy##name [(exp) ? 1 : -1]

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>