tcmode-default.inc: fix up
Fixed:
ERROR: Trying to resolve runtime dependency glibc resulted in conflicting PREFERRED_PROVIDER entries being found.
The providers found were: ['/path/to/wr-sdk-toolchain/recipes-devtools/toolchain/eglibc_sdk.bb', '/path/to/wr-base/recipes-core/eglibc/eglibc-initial_2.19.bb']
The PREFERRED_PROVIDER entries resulting in this conflict were: ['PREFERRED_PROVIDER_virtual/libc = eglibc', 'PREFERRED_PROVIDER_virtual/powerpc-wrs-linux-libc-initial = eglibc-initial']

Workaround for M2 TC.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>