guile: add append file back
Issue: LIN7-583

guile bbappend file is removed because gcc option '-fno-omit-frame-pointer'
is not a default value of wr toolchain any more. But when configured with
'--enable-build=debug', option of gcc '-fno-omit-frame-pointer' is added
into TARGET_CLFAGS. Then cause the failure again:

guile-2.0.11/libguile/vm-engine.c:168:1: error: r7 cannot be used in asm here

Add bbappend file back to make sure option '-fno-omit-frame-pointer' is
filtered out.

(LOCAL REV: NOT UPSTREAM) -- WR specified.

Signed-off-by: Kai Kang <kai.kang@windriver.com>